apiVersion: v1
kind: Service
metadata:
  name: apidemo-app
  labels:
    app: apidemo-app
    tier: apidemo-app
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: apidemo-app
    tier: apidemo-app
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: apidemo-app
  labels:
    app: apidemo
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: apidemo-app
        tier: apidemo-app
    spec:
      containers:
      - name: apidemo
        image: gcr.io/copper-imprint-193208/helloapidemo
        ports:
        - containerPort: 80 

   